### ISSUE TITLE
TypeError: Transformer "type-assertion" is resolving to a different Babel version to what is doing the actual transformation...

### ISSUE THREAD

**Issue by jackfranklin** [shuhei/babel-plugin-type-assertion#4]
Hey,

I'm trying to use this plugin but have hit a bit of a stumbling block. Loading it in like so:

```
require('babel/register')({
  plugins: [require('babel-plugin-type-assertion')],
});
```

But getting the following error:

```
TypeError: Transformer "type-assertion" is resolving to a different Babel version to what is doing the actual transformation...
    at Transformer.buildPass (/Users/jackfranklin/git/gocardless/react-splash-pages/node_modules/babel-plugin-type-assertion/node_modules/babel-core/lib/babel/transformation/transformer.js:130:13)
    at PluginManager.add (/Users/jackfranklin/git/gocardless/react-splash-pages/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:132:55)
    at File.buildTransformers (/Users/jackfranklin/git/gocardless/react-splash-pages/node_modules/babel-core/lib/babel/transformation/file/index.js:284:21)
```

However, doing `npm ls babel-core` confirms we are on the correct versions:

```
react-splash-pages@0.0.1 /Users/jackfranklin/git/gocardless/react-splash-pages
├── babel-core@5.2.17
└─┬ babel-plugin-type-assertion@0.1.0
  └── babel-core@5.2.17
```

I'm not entirely sure I understand what's going on or how to fix it. Any pointers you might have would be much appreciated, thank you!

**Comment by shuhei** [comment]
Ah, that's a restriction of babel plugin that it has to use the same babel-core module as the babel-core that actually do transformation. Can you add babel-core to your app's package.json if not yet, delete node_modules, and npm install? It will make babel-plugin-type-assertion to use the top level babel-core.

**Comment by jackfranklin** [comment]
Ahh I see, thank you. Unfortunately I'm now getting:

```
Error: Cannot find module 'rtts_assert/es6/src/rtts_assert'
```

And unsure how to debug / go forward with this. Thanks for your help so far, much appreciated!

**Comment by jackfranklin** [comment]
I got around the above by just doing `npm install rtts_assert` but now my next error is:

```
/Users/jackfranklin/git/gocardless/react-splash-pages/node_modules/rtts_assert/es6/src/rtts_assert.es6:31
export function proxy() {}
^^^^^^
SyntaxError: Unexpected reserved word
```

Do I need to tell Babel to compile this file? I presume by default it ignores `node_modules` ?

**Comment by shuhei** [comment]
Yes, at this time. Otherwise es5 version of rtts_assert still requires traceur runtime.

Sorry for the mess. This project is pretty experimental.

Here is a working webpack config. https://github.com/shuhei/accbook/blob/master/webpack.config.js

**Comment by shuhei** [comment]
I'll create an issue to make rtts_assert independent of traceur runtime and use this plugin to use the es5 version of rtts_assert.

**Comment by jackfranklin** [comment]
Awesome, thank you for your help :)

**Comment by shuhei** [comment]
In the meanwhile, the following code worked for me:

``` index.js
require('babel-core/register')({
  ignore: /node_modules\/(?!rtts_assert)/,
  plugins: ['type-assertion']
});

// Require your modules.
require('./hello');
```

``` hello.js
class Hello {
  say(name: string): string {
    return `Hello, ${name}`;
  }
}

// Correctly throws `Error: Invalid arguments given!`
console.log(new Hello().say(123));
```
